#version: '3.8'

services:
  bagisto:
    image: webkul/bagisto:2.3.5
    container_name: bagisto
    ports:
      - "8000:80"
    environment:
      APP_URL: http://185.222.163.113:8000
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: bagisto
      DB_USERNAME: bagisto
      DB_PASSWORD: bagisto123
    depends_on:
      - db
    volumes:
      - ./bagisto-entrypoint.sh:/usr/local/bin/bagisto-entrypoint.sh

  db:
    image: mysql:8.0
    container_name: bagisto-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: bagisto
      MYSQL_USER: bagisto
      MYSQL_PASSWORD: bagisto123
    volumes:
      - bagisto-data:/var/lib/mysql
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: bagisto-nginx
    restart: always
    ports:
      - "80:80"
      # - "443:443"  # uncomment if you want to handle SSL manually
    volumes:
      - ./geoip:/usr/share/GeoIP  # GeoIP database directory
      - ./public:/var/www/html/public
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - bagisto
volumes:
  bagisto-data:
